* <2020-09-04 Fri> init
  - can build reaper extension with meson
    worked on meson-iplug reaper, added the example there
  - added some first s7 reaper bindings
  - generated s7 functions that call reaper actions (actions beginning with =Item:= =Track:= and =Time Selection:=)
* <2020-09-05 Sat> (IM)Gui proof of concept
* <2020-09-06 Sun> how to handle multiple windows?
  Tried to modify SDL to make it work. Got somewhere but still had bugs (and would have to modify again for Windows - did the mods for linux)

  Started migrating to SFML
* <2020-09-07 Mon> migrated to SFML, can show multiple gui windows properly
  not bad at all for the 4th day of this :)
  Note: also VST3 is working properly now with multiple windows

  TODOs for today
  - [ ] draw from a gui =.scm= 
* TODO some TODOs/notes
  <2020-09-07 Mon> :
  - toolbar icon: can my action show active/inactive for gui scripts?
  - the concept of background scripts:
    - rpr/RegisterAction
    - rpr/RegisterBackgroundAction
    - rpr/RegisterGui
    the last 2 are running an event loop, the 1st is a one-time action
  - user scripts etc: sharing modules users should define their
    scripts in their own namespaces and thus be able to call other
    users' functions.
    
    EG: my region items could be exposed, anyone could embed it in their script
  - package manager for =.scm= scripts.. ughh
* <2020-09-07 Mon> SDL -> SFML

  |                    | size |
  | SDL                |   ?? |
  | SFML               | 21.4 |
  | SFML-sans graphics | 17.7 |

* SFML cannot listen to port??
  #+BEGIN_SRC sh :session *reaper-repl*
# start listening
nc -l -p 1234
fuser 1234/tcp
netstat -tulpn | grep 1234
netcat localhost 1234
cat /proc/sys/net/ipv4/tcp_fin_timeout
# default 60
echo 20 | sudo tee /proc/sys/net/ipv4/tcp_fin_timeout
sudo 
  #+END_SRC

  #+BEGIN_SRC sh :session *client*
netcat localhost 1234
  #+END_SRC

  That worked.. and now after this SFML worked..

  I think SFML has some issues with networking.. saw that commented somewhere as well... ugh


  maybe not.. i stumbled upon a scenario when =nc= cannot open the port.
  I think this happens when the app crashes.. I have to wait some time (30 secs?) till the port is avaiable..?
* DONE <2020-10-04 Sun> curl/json/freesound
  swell: dlopen() failed: libcm_libcurl.so: cannot open shared object file: No such file or directory

  fuck.. again the shared library problem (the reason I made SFML static..)

  Solution
  =build_rpath: '$ORIGIN/s7-reaper-lib'=  (in the meson shared_library definition)

  where =$ORIGIN= denotes the location of this shared library (=reaper_s7-reaper.so=).
  So I put =libcm_libcurl.so= into the =s7-reaper-lib= relative to the =reaper_s7-reaper.so= lib
* DONE <2020-10-05 Mon> adding a sample (from freesound)
  yay
  added 2 demo actions "Freesound: Insert random kick/snare"
* Ram consumption.. 10mb ?
  I notice a 10mb ram difference with the same project with =reaper_s7-reaper.so= loaded vs not loaded
* DONE <2020-10-07 Wed> gui crashing. plus repl crashing
  I was using s7 from the svn with bil's patch about the star functions and s7_free.
  Updated to the last revision =9.6+20200928=, and it's now ok
