;; auto-generated file. see gen.scm
(ns rpr.actions.time-selection
  :require ((rpr) (rpr.common)))
(define cmd rpr.common/cmd) ;; runs either native actions (with number id) or named actions (eg SWS)

(define (remove-time-selection-and-loop-points) (cmd 40020))
(define (shift-left-{by-time-selection-length}) (cmd 40037))
(define (shift-right-{by-time-selection-length}) (cmd 40038))
(define (nudge-left) (cmd 40039))
(define (nudge-right) (cmd 40040))
(define (crop-project-to-time-selection) (cmd 40049))
(define (move-cursor-left,-creating-time-selection) (cmd 40102))
(define (move-cursor-right,-creating-time-selection) (cmd 40103))
(define (insert-empty-space-at-time-selection-{moving-later-items}) (cmd 40200))
(define (remove-contents-of-time-selection-{moving-later-items}) (cmd 40201))
(define (set-time-selection-to-items) (cmd 40290))
(define (nudge-left-edge-left) (cmd 40320))
(define (nudge-left-edge-right) (cmd 40321))
(define (nudge-right-edge-left) (cmd 40322))
(define (nudge-right-edge-right) (cmd 40323))
(define (copy-time-selection-to-loop-points) (cmd 40622))
(define (copy-loop-points-to-time-selection) (cmd 40623))
(define (set-start-point) (cmd 40625))
(define (set-end-point) (cmd 40626))
(define (remove-time-selection) (cmd 40635))
(define (extend-time-selection-to-next-transient-in-items) (cmd 40802))
(define (swap-left-edge-of-time-selection-to-next-transient-in-items) (cmd 40803))
